export default class EffectType {
    static values = {
        "Transcript ablation": "transcript_ablation",
        "Splice acceptor": "splice_acceptor_variant",
        "Splice donor": "splice_donor_variant",
        "Stop gained": "stop_gained",
        "Frameshift": "frameshift_variant",
        "Stop lost": "stop_lost",
        "Start lost": "start_lost",
        "Transcript amplification": "transcript_amplification",
        "Feature elongation": "feature_elongation",
        "Feature truncation": "feature_truncation",
        "Inframe insertion": "inframe_insertion",
        "Inframe deletion": "inframe_deletion",
        "Missense": "missense_variant",
        "Protein altering": "protein_altering_variant",
        "Splice donor 5th base": "splice_donor_5th_base_variant",
        "Splice region": "splice_region_variant",
        "Splice donor region": "splice_donor_region_variant",
        "Splice polypyrimidine tract": "splice_polypyrimidine_tract_variant",
        "Incomplete terminal codon": "incomplete_terminal_codon_variant",
        "Start retained": "start_retained_variant",
        "Stop retained": "stop_retained_variant",
        "Synonymous": "synonymous_variant",
        "Coding sequence": "coding_sequence_variant",
        "Mature miRNA": "mature_miRNA_variant",
        "5 prime UTR": "5_prime_UTR_variant",
        "3 prime UTR": "3_prime_UTR_variant",
        "Non coding transcript exon": "non_coding_transcript_exon_variant",
        "Intron": "intron_variant",
        "NMD transcript": "NMD_transcript_variant",
        "Non coding transcript": "non_coding_transcript_variant",
        "Coding transcript": "coding_transcript_variant",
        "Upstream gene": "upstream_gene_variant",
        "Downstream gene": "downstream_gene_variant",
        "TFBS ablation": "TFBS_ablation",
        "TFBS amplification": "TFBS_amplification",
        "TF binding site": "TF_binding_site_variant",
        "Regulatory region ablation": "regulatory_region_ablation",
        "Regulatory region amplification": "regulatory_region_amplification",
        "Regulatory region": "regulatory_region_variant",
        "Intergenic": "intergenic_variant",
        "Sequence": "sequence_variant"
    };
}